language: java
jdk:
  - oraclejdk8
sudo: false
notifications:
  hipchat:
    rooms:
      secure: OlIO4DA0xfqdHqS2ytSfDucjIoncHBgLDFjDi1u+qsLOPBeYpYuNJOZkW531yKPFS/na8BjS5WzjrdZW1Wa2I41X2KdNEqOBPxCNsDlvRzEsMUXGCekTEkIaVKgyD8LsAqku+I0CFRsYCQCxRz6yufEenDf7VwdhbM/345mopkI=
deploy:
  provider: releases
  api_key:
    secure: cbqkrW9H5ivkPYgY34Fk8K8HWf2d90glxLoxPMkx+M8Kwxm/1tio9X8z9bze5wIJ4rozSOWmmn//MbB6TDhwiNABESxU5xQkmgJ45hV1anua88R50QgKwpK7OGX95v08b6iNfK9DKH+1BesgIjEf5ER5SK/48NkTYcuCO8Ku01SYHuT3V201X6vb9gWQQKGERr28DY4VoedFmCmgLP7bO+sBo9puTKfIUzyO6aycOKonLPDAefaypDAtOjbNWptvoQDcVDaJKMdahC5doUdm2IEJzW4CYn9kPvSujZWaIAzy/+72MJzR8LC2us16qVFJp63+mdEnh4EtrTTai1rOoXW+E3i9ZYIMVn2k275Mko63c6zcDrb97Mj1+osm9t/cwpqDyD787HBZCbnPzVPPgW20qRAR/2tUkwmiV0NGRumAMs1yvRt06Phl9al1iIaTV1LKXubmC2y4w6pr4u02qAz0evRbpGZcQ+TQDfEaPNs7Cph2GOgCCPRS1WdkNkAT2WZjW8K00qoSqXklW9uPgJ49SoBDiBm6pEjNnm7b4aSyY9cDAa7sJDj12LWtAQbpBWkfGLdk0wKV43XKpssFfn7JH2q5na4NgHT+6Ve99HbpT0vMVH+8jfplUpHgAqwy6UCmJ+TE8OhnH7TNHwBbZOGu79FV6zuW2dT797q9VQs=
  file: build/libs/xlr-overthere-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-overthere-plugin
